# Generated by Django 3.1.6 on 2021-02-11 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_query_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filtervalues',
            name='filter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.filter'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together={('user', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'student')},
        ),
    ]
