# Generated by Django 3.1.6 on 2021-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210211_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
