# Generated by Django 3.1.6 on 2021-02-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('student_about', models.TextField(blank=True, max_length=2048)),
                ('student_image', models.ImageField(upload_to='avatars')),
                ('status', models.IntegerField(default=0)),
                ('filters', models.ManyToManyField(to='main.FilterValues')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student')),
            ],
        ),
    ]
