# Generated by Django 3.1.6 on 2021-02-24 12:21

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprojects',
            name='project_name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprojects',
            name='project_pick',
            field=models.ImageField(default=None, upload_to=student.models.convert_fn),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(upload_to=student.models.convert_fn),
        ),
    ]
