# Generated by Django 3.1.6 on 2021-02-18 19:19

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(upload_to=student.models.convert_fn),
        ),
        migrations.CreateModel(
            name='StudentProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('project_pick', models.ImageField(upload_to=student.models.convert_fn)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student')),
            ],
        ),
    ]
