# Generated by Django 3.1.6 on 2021-02-22 11:58

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210218_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojects',
            name='project_pick',
            field=models.ImageField(default=None, upload_to=student.models.convert_fn),
        ),
    ]
