# Generated by Django 3.1.6 on 2021-02-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210224_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojects',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='student.student'),
        ),
    ]
