# Generated by Django 3.1.6 on 2021-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210318_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
