# Generated by Django 3.1.6 on 2021-04-03 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210318_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojects',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 3, 14, 44, 55, 318070), null=True),
        ),
    ]
