# Generated by Django 3.1.6 on 2021-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210403_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprojects',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
