# Generated by Django 3.1.6 on 2021-03-11 16:31

from django.db import migrations, models
import napa_recruitment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210222_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Пожалуйста, предоставьте свой телефон', max_length=15, unique=True, validators=[napa_recruitment.validators.PhoneValidator()]),
        ),
    ]
